linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    #- revive
    - gosec
    - govet
    - ineffassign
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
exclude-use-default: false

